# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: U:/180306_move_everything_from_pit9/180312_Integration_M4_update_debounce_LFSR/180312_Integration_M4_update_debounce_LFSR.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_axi_gpio_0_0/dma_design_1_axi_gpio_0_0.xci
# IP: The module: 'dma_design_1_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/180306_move_everything_from_pit9/180312_Integration_M4_update_debounce_LFSR/180312_Integration_M4_update_debounce_LFSR.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_axi_gpio_0_0/dma_design_1_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_design_1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: u:/180306_move_everything_from_pit9/180312_Integration_M4_update_debounce_LFSR/180312_Integration_M4_update_debounce_LFSR.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_axi_gpio_0_0/dma_design_1_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_design_1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: u:/180306_move_everything_from_pit9/180312_Integration_M4_update_debounce_LFSR/180312_Integration_M4_update_debounce_LFSR.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_axi_gpio_0_0/dma_design_1_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_design_1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: U:/180306_move_everything_from_pit9/180312_Integration_M4_update_debounce_LFSR/180312_Integration_M4_update_debounce_LFSR.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_axi_gpio_0_0/dma_design_1_axi_gpio_0_0.xci
# IP: The module: 'dma_design_1_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: u:/180306_move_everything_from_pit9/180312_Integration_M4_update_debounce_LFSR/180312_Integration_M4_update_debounce_LFSR.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_axi_gpio_0_0/dma_design_1_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_design_1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: u:/180306_move_everything_from_pit9/180312_Integration_M4_update_debounce_LFSR/180312_Integration_M4_update_debounce_LFSR.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_axi_gpio_0_0/dma_design_1_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_design_1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: u:/180306_move_everything_from_pit9/180312_Integration_M4_update_debounce_LFSR/180312_Integration_M4_update_debounce_LFSR.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_axi_gpio_0_0/dma_design_1_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_design_1_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
