# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/jfa49/180315_INTEGRATEwithoutVGAupdated/180315_INTEGRATEwithoutVGAupdated.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_processing_system7_0_0/dma_design_1_processing_system7_0_0.xci
# IP: The module: 'dma_design_1_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jfa49/180315_INTEGRATEwithoutVGAupdated/180315_INTEGRATEwithoutVGAupdated.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_processing_system7_0_0/dma_design_1_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_design_1_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/jfa49/180315_INTEGRATEwithoutVGAupdated/180315_INTEGRATEwithoutVGAupdated.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_processing_system7_0_0/dma_design_1_processing_system7_0_0.xci
# IP: The module: 'dma_design_1_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jfa49/180315_INTEGRATEwithoutVGAupdated/180315_INTEGRATEwithoutVGAupdated.srcs/sources_1/bd/dma_design_1/ip/dma_design_1_processing_system7_0_0/dma_design_1_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_design_1_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
